### ISSUE TITLE
Test LIO-SAM on the real robot

### ISSUE THREAD

**Issue by sergimolina** [LCAS/bacchus_lcas#16]

**Comment by ibrahimhroob** [comment]
Progress update: 
Issue #1: Image projection node keeps restarting: I found that the point cloud data that in coming from gazebo velodyne plugin does not follow the[ point cloud data stander](https://pcl.readthedocs.io/projects/tutorials/en/latest/basic_structures.html#basic-structures), in which if the cloud.height = 1, it means the datasets are unorganized, but for some reason the data that comes from velodyne plugin is the other way around! where the cloud.width was equal to 1 and that was causing a segmentation fault in PCL. 
To fix this issue I had just simply to swap the height and width data. 

Issue #2: Large velocity, reset IMU-preintegration: the scanned frames keeps jumping in random directions, I believe this issue is due to IMU calibration. The authors of LIO_SAM provides an external algorithm to do the calibration process, I tested it and the extrinsicRot was identity matrix, I think that make sense because the IMU gazebo plugin follows [ros 105](https://www.ros.org/reps/rep-0105.html). 
It still did not work as expected and more investigation need to be done!

**Comment by jediofgever** [comment]
Hi @ibrahimhroob , we’re you able to get some results ? 
I was also doing some tests with LIO-SAM recently. Are you purely running it in Gazebo or real data? 
I tried with live sensor data and ros bags. With ros bags I also had issues because of frame dropping. 

But when I used live sensor data I was able to get reasonable maps. My setup had Ouster-64 Lidar and a Xsens mti-30 IMU. 

I could share some visuals from the results if you want to see.

**Comment by ibrahimhroob** [comment]
Hi @jediofgever, yeah I was able to get some results on both gazebo and the real data. I did not notice the frame dropping issue but can you please share the results? have you tried only to play the imu and lidar topics from the bag? that may help especially if too many topics were recorded.

**Comment by jediofgever** [comment]
Hi, perhaps our aim and use case of LIO-SAM is  a bit different but still might be useful. 

For example this is the area that I like to build the map; 
![WTLP7270](https://user-images.githubusercontent.com/18460336/132196454-3903293f-fd6a-4bd9-82ea-c12e85a91ae6.JPG)

A similar perspective of acquired map the is; 
![Screenshot from 2021-09-06 11-43-02](https://user-images.githubusercontent.com/18460336/132196785-6e88b2e0-7dc4-470f-838c-1b8a2b35e792.png)


Green points are trajectory estimation
. There is an issue of dynamic objects being registered to map with LIOSAM. Is that causing any trouble to you as well ? 

I mainly need SLAM because I need dense maps that I use for uneven terrain navigation.
Are you also making use of created maps or you mainly need it for odometery estimation ?  
My finding is that, VSLAM approaches are working OK for odometry estimation but they are quite bad for building high quality dense maps. From your experience does any methods build better quality maps(less noise and less dynamic object registration)?

**Comment by jediofgever** [comment]
LIOSAM does a good job but it must be noted that I have an supplementary RTK GPS 
Here is how LIOSAM odometry compares to pure RTK

![Screenshot from 2021-08-23 12-54-58](https://user-images.githubusercontent.com/18460336/132197902-5e4fcc92-4b1d-4133-8c2c-84b8389c785a.png)

**Comment by ibrahimhroob** [comment]
The main issue with LIOSAM it does not understand the environment so it can not filter the dynamic objects. For my use case I was using it only for odometry estimation and my tests were done mainly in static environment. 

The results you got are really good, have you passed the GNSS topic to LIOSAM? or the odometry estimation was based only on lidar and IMU? 

There as another algorithm that can filter dynamic objects that is SuMa++ but it is mainly targeted for autonomous vehicle applications since it has a NN that was trained to semantically segment objects on kitti data-set.   

Regarding VSLAM approach, which SLAM algorithm did you used? what perception system the algorithm used?

**Comment by jediofgever** [comment]
> have you passed the GNSS topic to LIOSAM?

yes, I did not try without GNSS yet so I am not sure how it will perform without that gold quality RTK signals. My setup had  Ouster-64 LIDAR and Xsens IMU. Pricey toys. Yes that actually might help removing some of the object such as pedestrians, I should give it a try I think Thanks , Ibrahim.  

I used OpenVSLAM ,  in simulation it does perform really good, in real just OK and thats only for odometry estimation. 
It might be good to see some results from simulation results of OpenVSLAM in case you wonder ; https://vox-nav.readthedocs.io/en/latest/openvslam/index.html

**Comment by ibrahimhroob** [comment]
Yeah that is very expensive setup. 

I was aware of OpenVSLAM system, but I did not use it since it was heavily based on ORB-SLAM2 and it has been terminated by the authors.  

I would recommend to try RTAB-MAP if you have not tried it already, the system is hugely configurable, where it is possible to use laser scanners for odometry estimation and the visual inputs to create a dense map. 

There is another system I came cross but did not try it yet that is [Kimera ](https://github.com/MIT-SPARK/Kimera)
