### ISSUE TITLE
Compare output between Zed2 and Realsense in outdoor enviroments 

### ISSUE THREAD

**Issue by sergimolina** [LCAS/bacchus_lcas#22]

**Comment by KarolineH** [comment]
|| ZED  | Realsense D435i |
|--| ------------- | ------------- |
|method| passive stereo vision | active IR stereo  |
|range| 0.3 - 25 m  | 0.3m - 3m  |
|FoV| 90°x60°| 86°x57°|
|depth accuracy| 1% near, <br />up to 9% at far range| <2% at 2m|
|depth resolution|2k @ 15fps <br />1080p @ 30fps | 1280x720 @ 30fps |
|outputs| left video<br /> right video<br /> depth map<br />IMU<br />camera position<br />constructed 3D map | left IR video <br /> right IR video <br />RGB video<br />depth map<br />IMU<br />color point cloud |

more to follow

**Comment by KarolineH** [comment]
The ZED 2 camera seems to be a good choice for SLAM applications for its great image resolution, robustness to light and outdoor scenarios, and long range. It's already mounted on the robot as well, however, it uses cuda so requires Nvidia GPU on board. I found some literature suggesting that the Realsense camera is better suited for close-range crop inspection purposes:

- Sensors which only use visible light imaging struggle to find correspondences in plants due to heavy (self-)occlusion and lack of surface texture. Most crops have smooth and shiny surfaces with few salient textural features and also appear similar in colour all over [1]. This suggests that active IR technology of the Realsense camera is more suited for close-range inspection of the plants.
- [2] report that the ZED (previous generation to the ZED 2) camera is prone to flaws and inaccuracies at close range, including depths errors
- The comparison study in [3] found the ZED camera (previous generation to the ZED 2) not suitable for fruit inspection based on a number of tests on different materials and lighting conditions, especially in comparison with other RGB-D devices. 
- Considering Kinect: A comparison in [4] shows that the Kinect ii depth performance drops at higher light intensities and especially in direct sunlight, much more so than for the Intel d435.


[1] Pound, M.P., French, A.P., Murchie, E.H. and Pridmore, T.P., 2014. Automated recovery of three-dimensional models of plant shoots from multiple color images. Plant physiology, 166(4), pp.1688-1698.
[2] Condotta, I.C., Brown-Brandl, T.M., Pitla, S.K., Stinn, J.P. and Silva-Miranda, K.O., 2020. Evaluation of low-cost depth cameras for agricultural applications. Computers and Electronics in Agriculture, 173, p.105394.
[3] Wang, Z., Walsh, K.B. and Verma, B., 2017. On-tree mango fruit size estimation using RGB-D images. Sensors, 17(12), p.2738.
[4] Vit, A. and Shani, G., 2018. Comparing RGB-D sensors for close range outdoor agricultural phenotyping. Sensors, 18(12), p.4413.

**Comment by KarolineH** [comment]
Here are some images taken from [2]. The left panel shows the depth map recorded by the ZED camera (first generation), right shows the Intel RealSense D435. The image below shows RGB image of the tested scenario for reference.
<img width="653" alt="Screenshot 2021-04-23 at 11 50 03" src="https://user-images.githubusercontent.com/36478431/115860952-1e5e2480-a42a-11eb-9680-6948a5072a3f.png">
<img width="396" alt="Screenshot 2021-04-23 at 11 50 17" src="https://user-images.githubusercontent.com/36478431/115860968-23bb6f00-a42a-11eb-91e5-e3baa318ff6a.png">
